# Generated by Django 4.0.3 on 2022-06-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=10, verbose_name='음식')),
                ('meat', models.BooleanField(default=False, verbose_name='고기')),
                ('sea', models.BooleanField(default=False, verbose_name='해산물')),
                ('spicy', models.BooleanField(default=False, verbose_name='매움')),
                ('country', models.CharField(max_length=2, verbose_name='국가')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.BooleanField(default=False)),
                ('second', models.BooleanField(default=False)),
                ('third', models.BooleanField(default=False)),
            ],
        ),
    ]
