# Generated by Django 4.0.5 on 2022-06-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=10)),
                ('main', models.CharField(max_length=5)),
                ('soup', models.CharField(max_length=5)),
                ('meat', models.CharField(max_length=5)),
                ('spicy', models.CharField(max_length=5)),
                ('oily', models.CharField(max_length=5)),
            ],
        ),
    ]
