# Generated by Django 4.0.5 on 2022-06-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muki_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='main',
        ),
        migrations.RemoveField(
            model_name='food',
            name='oily',
        ),
        migrations.RemoveField(
            model_name='food',
            name='soup',
        ),
        migrations.AddField(
            model_name='food',
            name='raw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='sea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='ulken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='meat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='spicy',
            field=models.BooleanField(default=False),
        ),
    ]
