# Generated by Django 4.0.5 on 2022-06-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muki_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
