# Generated by Django 4.0.5 on 2022-06-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muki_main', '0002_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='spicy',
            new_name='hot',
        ),
    ]
