# Generated by Django 4.0.5 on 2022-06-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muki_main', '0004_food_meal_type_food_meat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cooking_type',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='country',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='meat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='meat_type',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='food',
            name='sea',
            field=models.BooleanField(default=False),
        ),
    ]
