# Generated by Django 4.0.5 on 2022-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muki_main', '0005_food_cooking_type_alter_food_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cooking_type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='meal_type',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='meat_type',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
