# Generated by Django 4.0.5 on 2022-06-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muki_main', '0006_alter_food_cooking_type_alter_food_meal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='meal_type',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
