# Generated by Django 4.0.5 on 2022-06-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muki_main', '0007_alter_food_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='cooking_type',
        ),
        migrations.AddField(
            model_name='food',
            name='seafood_type',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
