# Generated by Django 4.0.5 on 2022-06-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muki_main', '0008_remove_food_cooking_type_food_seafood_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='sea',
            new_name='seafood',
        ),
    ]
