# Generated by Django 4.0.4 on 2022-06-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='post',
        ),
    ]
