# Generated by Django 4.0.4 on 2022-06-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_post_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(default='서울', max_length=10),
            preserve_default=False,
        ),
    ]
