# Generated by Django 4.0.4 on 2022-06-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_post_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(choices=[('서울', '서울'), ('수원', '수원'), ('용인', '용인'), ('부산', '부산'), ('김해', '김해')], max_length=10),
        ),
    ]
